projects:
  app:
    schemaPath: db/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: db/generated/prisma.graphql
    extensions:
      prisma: db/prisma.yml