projects:
  app:
    schemaPath: src/graphql-server/schema.graphql
    extensions:
      endpoints:
        default: http://${PRISMA_ENDPOINT}
  database:
    schemaPath: src/graphql-server/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml