version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
      - "0.0.0.0:4400:4400"
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4400
        managementApiSecret: redqueen
        databases:
          default:
            connector: mysql
            host: lkredqueendb.cpyyl4afku4h.us-east-1.rds.amazonaws.com
            port: 3306
            user: redqueen
            password: redqueen
            migrations: true
            rawAccess: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: